# NumPy 연습 문제 1

In [1]:
import numpy as np

## [Part1] 연습문제 

### 문제 1.
길이가 10인 0-벡터를 만드세요.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 문제 2.
길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 문제 3.
10 부터 49까지의 값을 가지는 벡터를 만드세요.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 문제 5.
0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 문제 6.

3x3 단위 행렬(identity matrix)을 만드세요

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 문제 7.

0부터 15까지의 값을 가지는 3x5행렬을 만들고, arr 저장하세요.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 문제 8.

위의 arr에서 배열 [6,7]을 슬라이싱하세요. 

array([6, 7])

### 문제 9.

위의 arr에서 배열 [[3,4], [8,9]]를 슬라이싱하세요. 

array([[3, 4],
       [8, 9]])

### 문제 10.

위의 arr에서 배열 [[0, 1, 2], [5, 6, 7], [10, 11, 12]]를 슬라이싱하세요. 

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])