# [NumPy 연습 문제]

In [1]:
import numpy as np

#### 연습문제 1. 배열 재형성하기
아래 arr 배열을 4x5 행렬로 변환하세요.

In [23]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### 연습문제 2. 배열 재형성하기 
5x4 shape을 가진 배열 선언 후, 1차원으로 변환하세요

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 연습문제 3. 배열 이어붙이기

아래 3개 배열을 1차원으로 결합하세요. 
- x : [1, 2, 3]
- y : [3, 2, 1]
- z : [99, 99]

array([ 1,  2,  3,  3,  2,  1, 99, 99])

아래 2차원 2개 배열을 첫번째 축을 따라 연결하세요
- x : [[1, 2, 3], [4, 5, 6]]
- y : [[1, 1, 1], [2, 2, 2]]

[[1 2 3]
 [4 5 6]
 [1 1 1]
 [2 2 2]]
[[1 2 3]
 [4 5 6]
 [1 1 1]
 [2 2 2]]


아래 2차원 2개 배열을 두번째 축을 따라 연결하세요
- x : [[1, 2, 3], [4, 5, 6]]
- y : [[1, 1, 1], [2, 2, 2]]

[[1 2 3 1 1 1]
 [4 5 6 2 2 2]]
[[1 2 3 1 1 1]
 [4 5 6 2 2 2]]


#### 연습문제 4. 브로드 캐스팅
아래 10x3 배열을 중앙 정렬하세요. (X - X_mean)
- X : (10x3) shape을 가진 matrix
- X_mean : 각 열의 평균값 (3, )

In [16]:
X = np.arange(30).reshape((10,3))
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

array([[-13.5, -13.5, -13.5],
       [-10.5, -10.5, -10.5],
       [ -7.5,  -7.5,  -7.5],
       [ -4.5,  -4.5,  -4.5],
       [ -1.5,  -1.5,  -1.5],
       [  1.5,   1.5,   1.5],
       [  4.5,   4.5,   4.5],
       [  7.5,   7.5,   7.5],
       [ 10.5,  10.5,  10.5],
       [ 13.5,  13.5,  13.5]])

array([0., 0., 0.])