# [NumPy 연습 문제]

In [1]:
import numpy as np

#### 연습문제 1. 배열 재형성하기
아래 arr 배열을 4x5 행렬로 변환하세요.

In [2]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### 연습문제 2. 배열 재형성하기 
5x4 shape을 가진 배열 선언 후, 1차원으로 변환하세요

In [4]:
arr.reshape(4,5).reshape(5,4).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 연습문제 3. 배열 이어붙이기

아래 3개 배열을 1차원으로 결합하세요. 
- x : [1, 2, 3]
- y : [3, 2, 1]
- z : [99, 99]

In [5]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99])

In [6]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99])

아래 2차원 2개 배열을 첫번째 축을 따라 연결하세요
- x : [[1, 2, 3], [4, 5, 6]]
- y : [[1, 1, 1], [2, 2, 2]]

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 1, 1], [2, 2, 2]])

아래 2차원 2개 배열을 두번째 축을 따라 연결하세요
- x : [[1, 2, 3], [4, 5, 6]]
- y : [[1, 1, 1], [2, 2, 2]]

#### 연습문제 4. 브로드 캐스팅
아래 10x3 배열을 중앙 정렬하세요. (X - X_mean)
- X : (10x3) shape을 가진 matrix
- X_mean : 각 열의 평균값 (3, )

In [23]:
X_mean = X.mean(axis=1)

In [24]:
X_mean.shape

(10,)

In [21]:
X = np.arange(30).reshape((10,3))
X.shape

(10, 3)

In [25]:
X - X_mean

ValueError: operands could not be broadcast together with shapes (10,3) (10,) 

In [26]:
arr = np.arange(120).reshape(3,4,5,2)

In [42]:
arr[:,:,:,0] - arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [43]:
arr[:,:,:,1] - arr1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [28]:
arr1 = np.arange(60).reshape(3,4,5)

In [39]:
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [45]:
arr - arr1.reshape(3,4,5,1)

array([[[[ 0,  1],
         [ 1,  2],
         [ 2,  3],
         [ 3,  4],
         [ 4,  5]],

        [[ 5,  6],
         [ 6,  7],
         [ 7,  8],
         [ 8,  9],
         [ 9, 10]],

        [[10, 11],
         [11, 12],
         [12, 13],
         [13, 14],
         [14, 15]],

        [[15, 16],
         [16, 17],
         [17, 18],
         [18, 19],
         [19, 20]]],


       [[[20, 21],
         [21, 22],
         [22, 23],
         [23, 24],
         [24, 25]],

        [[25, 26],
         [26, 27],
         [27, 28],
         [28, 29],
         [29, 30]],

        [[30, 31],
         [31, 32],
         [32, 33],
         [33, 34],
         [34, 35]],

        [[35, 36],
         [36, 37],
         [37, 38],
         [38, 39],
         [39, 40]]],


       [[[40, 41],
         [41, 42],
         [42, 43],
         [43, 44],
         [44, 45]],

        [[45, 46],
         [46, 47],
         [47, 48],
         [48, 49],
         [49, 50]],

        [[50, 51],
       

In [29]:
arr2 = np.arange(30).reshape(3,5,2)

In [30]:
arr3 = np.arange(12).reshape(3,4,5,2)