# 1. 배열 재형성하기

In [31]:
import numpy as np

In [32]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

###### <span style="color:blue">Example 1. reshape</span>

In [33]:
arr.shape

(8,)

In [34]:
# (8,) --> (4,2)shape으로 변경
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [35]:
# (8,) --> (4,2) --> (2,4) shape으로 변경 
arr.reshape(4,2).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
# (15, ) --> (5, -1) shape으로 변경
arr = np.arange(15)
np.arange(15).reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

- reshape에 넘기는 값 중 하나는 -1이 될 수도 있는데, 이 경우에는 원본 데이터를 참조해서 적절한 값을 추론하게 됩니다.

In [42]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [44]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

###### <span style="color:blue">Example 2. </span>

In [53]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
np.ravel?

In [48]:
arr = np.arange(300).reshape(10, 3, -1)

In [51]:
arr.ravel().shape

(300,)

In [54]:
# (2,4) --> ravel
np.ravel(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
# (2,4) --> flatten 
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

# 2. 배열 이어붙이고 나누기

- concatenate:  axis에 따라서 하나의 배열로 합친다.

In [56]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

In [57]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

###### <span style="color:blue">Example 3</span>

In [60]:
np.concatenate?

In [73]:
# axis=0 기준으로 배열 합치기
arr4 = np.concatenate([arr1, arr2], axis=0)

In [74]:
arr4.shape

(4, 3)

In [71]:
# axis=1 기준으로 배열 합치기
arr3 = np.concatenate([arr1, arr2], axis=1)
arr3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [72]:
arr3.shape

(2, 6)

- vstack: vertical
- hstack: horizontal

In [78]:
np.vstack((arr1, arr2, arr1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [76]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# 3. 브로드캐스팅

- 브로드캐스팅은 다른 모양의 배열 간 산술연산을 어떻게 수행해야 하는지 설명한다. 이는 매우 강력한 기능이다. 

In [79]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [80]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [81]:
arr.shape

(5,)

###### <span style="color:blue">Example 4</span>

In [83]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
arr.shape

(4, 3)

In [97]:
arr_mean.shape

(1, 3)

In [92]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
# axis=0 기준 평균 (arr_mean)
arr_mean = arr.mean(0).reshape(1, 3)
np.concatenate([arr_mean, arr_mean, arr_mean, arr_mean], axis=0)

array([[4.5, 5.5, 6.5],
       [4.5, 5.5, 6.5],
       [4.5, 5.5, 6.5],
       [4.5, 5.5, 6.5]])

In [96]:
# arr, arr_mean 차 
arr - arr_mean

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

- 브로드캐스팅 규칙을 따르기만 한다면 잠재적으로 낮은 차원의 값을 배열의 다른 차원으로 브로드캐스팅 하는 것도 가능하다.

### 브로드 캐스팅 규칙

- 만일 이어지는 각 차원(시작부터 끝까지)에 대해 축의 길이가 일치하거나 둘 중의 하나의 길이가 1이라면 두 배열은 브로드캐스팅 호환이다. 브로드캐스팅은 누락된, 혹은 길이가 1인 차원에 대해 수행된다.

In [110]:
import numpy as np

In [111]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [101]:
arr.shape

(4, 3)

In [112]:
arr.mean(axis=1)

array([ 1.,  4.,  7., 10.])

In [113]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [114]:
row_means.reshape((4,1))

array([[ 1.],
       [ 4.],
       [ 7.],
       [10.]])

In [115]:
arr.shape

(4, 3)

In [116]:
row_means.shape

(4,)

In [107]:
print(arr)
arr.shape

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


(4, 3)

In [108]:
print(row_means)
row_means.shape

[ 1.  4.  7. 10.]


(4,)

In [119]:
arr, row_means

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([ 1.,  4.,  7., 10.]))

In [136]:
arr1 = row_means

In [125]:
arr.shape

(4, 3)

In [126]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [124]:
arr1.shape

(4, 1)

In [128]:
arr 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
arr2 = arr.mean(axis=0)
arr2.

array([4.5, 5.5, 6.5])

In [142]:
arr.shape

(4, 3)

In [141]:
arr2.shape

(3,)

In [137]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [138]:
arr - arr1

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [140]:
arr - arr2

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [80]:
demeaned.mean(1)

array([0., 0., 0., 0.])

###### <span style="color:blue"> Examaple 5. 브로드 캐스팅 규칙 설명</span>

- 다른 축에 대해 브로드 캐스팅하기

In [12]:
arr = np.random.randn(4, 3)
arr

array([[ 0.7603179 , -0.1420891 ,  0.20257845],
       [ 0.55401034,  0.56647534,  0.70976265],
       [ 0.56885936,  0.88943027,  0.55571606],
       [ 1.29112265, -1.40834648, -1.55765142]])

In [13]:
# arr shape : (4,3)
# arr.mean(1) : (4,)

arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [14]:
arr.shape

(4, 3)

In [15]:
arr.mean(1).shape

(4,)

In [89]:
# arr.mean(1) 의 shape 변경 필요


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

- 브로드 캐스팅 이용해 배열에 값 대입하기

In [24]:
arr = np.zeros((4, 3))

In [25]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [27]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [30]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [21]:
arr[:] = col[:, np.newaxis]

In [22]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [71]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [72]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

# Broad Casting

In [150]:
arr = np.arange(12).reshape(4, 3)
print(arr.shape)

(4, 3)


In [182]:
arr1 = arr.mean(axis=0)
print(arr1.shape)

(3,)


In [187]:
arr2 = arr.mean(axis=1)
print(arr2.shape)

(4,)


In [188]:
arr - arr1

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [190]:
arr2.reshape(1, 4).shape

(1, 4)

In [193]:
arr - arr2.reshape(4, 1)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [194]:
new_arr = np.arange(60).reshape(5,4,3)
new_arr.shape

(5, 4, 3)

In [195]:
new_arr1 = new_arr.mean(axis=0)
new_arr1.shape

(4, 3)

In [196]:
new_arr2 = new_arr.mean(axis=1)
new_arr2.shape

(5, 3)

In [197]:
new_arr3 = new_arr.mean(axis=2)
new_arr3.shape

(5, 4)

In [198]:
new_arr - new_arr1

array([[[-24., -24., -24.],
        [-24., -24., -24.],
        [-24., -24., -24.],
        [-24., -24., -24.]],

       [[-12., -12., -12.],
        [-12., -12., -12.],
        [-12., -12., -12.],
        [-12., -12., -12.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[ 12.,  12.,  12.],
        [ 12.,  12.,  12.],
        [ 12.,  12.,  12.],
        [ 12.,  12.,  12.]],

       [[ 24.,  24.,  24.],
        [ 24.,  24.,  24.],
        [ 24.,  24.,  24.],
        [ 24.,  24.,  24.]]])

In [202]:
new_arr.shape

(5, 4, 3)

In [204]:
new_arr2.reshape(5,1,3).shape

(5, 1, 3)

In [201]:
new_arr - new_arr2.reshape(5,1,3)

array([[[-4.5, -4.5, -4.5],
        [-1.5, -1.5, -1.5],
        [ 1.5,  1.5,  1.5],
        [ 4.5,  4.5,  4.5]],

       [[-4.5, -4.5, -4.5],
        [-1.5, -1.5, -1.5],
        [ 1.5,  1.5,  1.5],
        [ 4.5,  4.5,  4.5]],

       [[-4.5, -4.5, -4.5],
        [-1.5, -1.5, -1.5],
        [ 1.5,  1.5,  1.5],
        [ 4.5,  4.5,  4.5]],

       [[-4.5, -4.5, -4.5],
        [-1.5, -1.5, -1.5],
        [ 1.5,  1.5,  1.5],
        [ 4.5,  4.5,  4.5]],

       [[-4.5, -4.5, -4.5],
        [-1.5, -1.5, -1.5],
        [ 1.5,  1.5,  1.5],
        [ 4.5,  4.5,  4.5]]])

In [205]:
new_arrr = np.arange(120).reshape(4,3,5,2)
new_arrr.shape

(4, 3, 5, 2)

In [206]:
new_arrr2 = np.arange(20).reshape(4, 5)

In [211]:
new_arrr2.reshape(4,1,5,1)

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4]]],


       [[[ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]]],


       [[[10],
         [11],
         [12],
         [13],
         [14]]],


       [[[15],
         [16],
         [17],
         [18],
         [19]]]])

In [209]:
new_arrr - new_arrr2.reshape(4, 1, 5, 1)

array([[[[  0,   1],
         [  1,   2],
         [  2,   3],
         [  3,   4],
         [  4,   5]],

        [[ 10,  11],
         [ 11,  12],
         [ 12,  13],
         [ 13,  14],
         [ 14,  15]],

        [[ 20,  21],
         [ 21,  22],
         [ 22,  23],
         [ 23,  24],
         [ 24,  25]]],


       [[[ 25,  26],
         [ 26,  27],
         [ 27,  28],
         [ 28,  29],
         [ 29,  30]],

        [[ 35,  36],
         [ 36,  37],
         [ 37,  38],
         [ 38,  39],
         [ 39,  40]],

        [[ 45,  46],
         [ 46,  47],
         [ 47,  48],
         [ 48,  49],
         [ 49,  50]]],


       [[[ 50,  51],
         [ 51,  52],
         [ 52,  53],
         [ 53,  54],
         [ 54,  55]],

        [[ 60,  61],
         [ 61,  62],
         [ 62,  63],
         [ 63,  64],
         [ 64,  65]],

        [[ 70,  71],
         [ 71,  72],
         [ 72,  73],
         [ 73,  74],
         [ 74,  75]]],


       [[[ 75,  76],
         [

### Broadcasting은 3가지 동작으로 진행됩니다.

#### 1. padding - 고차원 방향으로만 진행이 된다.
#### 2. copy - 차원 1인 것을 해당 차원에 맞게 확장해서 연산한다.
#### 3. operation - 연산한다.