In [44]:
import numpy as np

In [27]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

5

In [6]:
arr[5:7] = 3

In [8]:
arr

array([0, 1, 2, 3, 4, 3, 3, 7, 8, 9])

In [16]:
lst = [i for i in range(10)]

In [21]:
lst1[5:7] = [3] * 3

In [20]:
lst1 = lst[:]

In [22]:
lst1

[0, 1, 2, 3, 4, 3, 3, 3, 7, 8, 9]

In [23]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
arr1 = arr[5:7]

In [41]:
arr1 += 3

In [42]:
arr

array([0, 1, 2, 3, 4, 8, 9, 7, 8, 9])

In [43]:
arr

array([0, 1, 2, 3, 4, 8, 9, 7, 8, 9])

In [39]:
arr1

6