In [2]:
import numpy as np

# 1. Universal 함수

ufunc라고 불리는 유니버셜 함수는 ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수이다. 유니버셜 함수는 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과 값을 반환하는 간단한 함수를 고속으로 수행할 수 있는 백터화된 래퍼 함수라고 생각하면 된다.

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [0]:
x = np.random.randn(8)
y = np.random.randn(8)

In [0]:
np.maximum(x, y) # element wise operation

array([-1.4423063 ,  0.15591954,  0.35655707,  1.9711139 ,  1.33431801,
        0.55076497,  1.65486003,  0.37015179])

### 단항 유니버셜 함수

- abs: 각 원소의 절대값을 구한다.
- sqrt: 각 원소의 제곱근을 구한다.
- square: 각 원소의 제곱을 구한다.
- sign: 각 원소의 부호를 계산한다.
- ceil, floor: 각 원소의 소수자리를 올리거나 내린다.
- rint: 각 원소의 소수자리를 반올림한다.
- sin, cos, tan: 일반 삼각함수
- sinh, cosh, tanh: 쌍곡삼각 함수
- arccos, arccosh, arcsinh: 역삼각함수

### 이항 유니버셜 함수

- add, subtract, multiply: 두 배열에서 같은 위치 원소끼리 더하고, 빼고, 곱한다.
- divide: 첫 번째 배열에서 두 번째 배열의 원소를 나눈다.
- power: 첫 번째 배열의 원소에 두 번째 배열의 원소만큼 제곱한다.
- maximum, minimum: 두 원소 중 큰 값, 작은 값을 반환한다.
- mod: 첫 번째 배열의 원소에 두 번째 배열의 원소를 나눈 나머지를 구한다.
- greater, less, equal: 각각 두 원소 간의 비교 연산 결과를 불리언 배열로 반환한다.
- logical_and, logical_or, logical_xor: 각각 두 원소 간의 논리 연산을 배열로 반환한다.

# 2. 배열 연산

### 1. 조건절 표현하기

In [0]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [0]:
result = np.where(cond, xarr, yarr)

In [0]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
arr = np.random.randn(4, 4)
arr

array([[-0.06151794, -1.09937216, -0.3238963 ,  0.9723139 ],
       [-1.04576512,  1.68735391, -0.25837225,  0.19800455],
       [ 0.02008683,  1.5118426 ,  0.90752229,  0.04042003],
       [-2.1873865 , -0.17624809, -0.14246374,  0.07332915]])

In [10]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2,  2],
       [-2,  2, -2,  2],
       [ 2,  2,  2,  2],
       [-2, -2, -2,  2]])

### 2. 수학 메서드와 통계 메서드

배열 전체 혹은 배열에서 한 축에 따르는 자료에 대한 통계를 계산하기 위한 수학 함수는 배열 메서드로 사용할 수 있다. 전체의 합이나 평균, 표준편차는 Numpy의 최상위 함수를 이용하거나, 배열의 인스턴스 메서드를 사용해서 구할 수 있다.

In [3]:
arr = np.random.rand(5, 4)
arr

array([[0.6188411 , 0.25080158, 0.32615459, 0.80098471],
       [0.49581152, 0.83142975, 0.13732407, 0.25260418],
       [0.04058447, 0.19629556, 0.74068295, 0.11075793],
       [0.41734836, 0.27346206, 0.98758177, 0.80306364],
       [0.03562774, 0.56174066, 0.66179141, 0.09367558]])

In [4]:
arr.mean()

0.4318281811186714

In [5]:
np.mean(arr)

0.4318281811186714

- mean이나 sum 같은 함수는 선택적으로 axis 인자를 받아 해당 axis에 대한 통계를 계산하고 차수 낮은 배열을 반환한다.

In [6]:
arr.sum()

8.636563622373428

In [7]:
arr.mean(axis=1)

array([0.4991955 , 0.42929238, 0.27208023, 0.62036395, 0.33820885])

In [0]:
arr.sum(0)

array([2.42802904, 2.30542711, 2.19394931, 1.36159996])

In [0]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [0]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [0]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### 3. 정렬

- np.sort 메서드는 배열을 직접 변경하지 않고 정렬된 결과를 가지고 있는 복사본을 반환한다.

In [0]:
arr = np.random.randn(8)
arr

array([-0.72457977,  0.87587823,  1.2289314 , -0.28894393,  0.15205621,
        0.39222443, -1.86491412, -0.43901666])

In [0]:
arr.sort()
arr

array([-1.86491412, -0.72457977, -0.43901666, -0.28894393,  0.15205621,
        0.39222443,  0.87587823,  1.2289314 ])

In [0]:
arr = np.random.randn(5, 3)
arr

array([[ 1.6184662 , -1.08623178, -0.94366897],
       [-0.48770058,  0.19617067, -1.26855797],
       [-0.43161619, -0.80774082,  1.70783631],
       [-1.05988322, -0.69291836, -0.12831549],
       [-0.2984775 ,  0.07530742, -1.90711257]])

In [0]:
arr.sort(1)
arr

array([[-1.08623178, -0.94366897,  1.6184662 ],
       [-1.26855797, -0.48770058,  0.19617067],
       [-0.80774082, -0.43161619,  1.70783631],
       [-1.05988322, -0.69291836, -0.12831549],
       [-1.90711257, -0.2984775 ,  0.07530742]])

## 3. 선형대수

### 내적은 중요하다.

In [15]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])
y = np.array([[6.,23.], [-1, 7], [8, 9]])

(2, 3)
(3, 2)


In [0]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [4]:
from numpy.linalg import inv

In [5]:
X = np.random.randn(5, 5)

In [6]:
mat = X.T.dot(X)

In [7]:
inv(mat)

array([[ 0.28486487,  0.125303  , -0.10945001, -0.18919413, -0.05637232],
       [ 0.125303  ,  0.46824161,  0.17906984, -0.94156494,  0.0345903 ],
       [-0.10945001,  0.17906984,  0.90633226, -0.27829464,  0.4187701 ],
       [-0.18919413, -0.94156494, -0.27829464,  3.93398709,  0.17475516],
       [-0.05637232,  0.0345903 ,  0.4187701 ,  0.17475516,  0.42030461]])