In [1]:
import numpy as np

# 1. 배열 재형성하기

In [55]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [56]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [57]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
arr = np.arange(15).reshape((5, -1))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

- reshape에 넘기는 값 중 하나는 -1이 될 수도 있는데, 이 경우에는 원본 데이터를 참조해서 적절한 값을 추론하게 됩니다.

In [59]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [60]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
#arr = np.arange(8)

a = arr.ravel()
b = arr.flatten()

print(arr)
print(id(.ravel())
print(id(flatten()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [64]:
#arr = np.arange(8)

a = arr.ravel()
b = arr.flatten()

In [9]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 2. 배열 이어붙이고 나누기

- concatenate:  axis에 따라서 하나의 배열로 합친다.

In [11]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

In [12]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- vstack: vertical
- hstack: horizontal

In [14]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# 3. 브로드캐스팅

- 브로드캐스팅은 다른 모양의 배열 간 산술연산을 어떻게 수행해야 하는지 설명한다. 이는 매우 강력한 기능이다. 

In [18]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [19]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [22]:
arr = np.random.randn(4, 3)
arr

array([[ 1.56404053,  0.09956201,  0.31560042],
       [-1.41929603,  0.98733789, -1.1162068 ],
       [-0.58501167, -0.75729012, -0.23114476],
       [-1.47913919,  0.78770946, -0.7313576 ]])

In [26]:
arr.mean(axis=0)

array([-0.47985159,  0.27932981, -0.44077718])

In [28]:
arr - arr.mean(axis=0)

array([[ 2.04389212, -0.1797678 ,  0.7563776 ],
       [-0.93944444,  0.70800808, -0.67542962],
       [-0.10516008, -1.03661993,  0.20963243],
       [-0.9992876 ,  0.50837965, -0.29058041]])

- 브로드캐스팅 규칙을 따르기만 한다면 잠재적으로 낮은 차원의 값을 배열의 다른 차원으로 브로드캐스팅 하는 것도 간으하다.

### 브로드 캐스팅 규칙

- 만일 이어지는 각 차원(시작부터 끝까지)에 대해 축의 길이가 일치하거나 둘 중의 하나의 길이가 1이라면 두 배열은 브로드캐스팅 호환이다. 브로드캐스팅은 누락된, 혹은 길이가 1인 차원에 대해 수행된다.

In [30]:
arr

array([[ 1.56404053,  0.09956201,  0.31560042],
       [-1.41929603,  0.98733789, -1.1162068 ],
       [-0.58501167, -0.75729012, -0.23114476],
       [-1.47913919,  0.78770946, -0.7313576 ]])

In [31]:
row_means = arr.mean(1)

In [33]:
row_means.reshape((4,1))

array([[ 0.65973432],
       [-0.51605498],
       [-0.52448218],
       [-0.47426244]])

In [34]:
demeaned = arr - row_means.reshape((4, 1))

In [35]:
demeaned.mean(1)

array([-1.85037171e-17,  7.40148683e-17,  3.70074342e-17, -5.55111512e-17])

- 다른 축에 대해 브로드 캐스팅하기

In [39]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [36]:
arr.shape

(4, 3)

In [38]:
arr.mean(1).shape

(4,)

In [40]:
arr - arr.mean(1).reshape((4,1))

array([[ 0.90430621, -0.56017231, -0.3441339 ],
       [-0.90324105,  1.50339287, -0.60015182],
       [-0.06052949, -0.23280794,  0.29333743],
       [-1.00487675,  1.2619719 , -0.25709516]])

- 3차원의 경우 세 가지 차원 중 어느 하나에 대한 브로드캐스팅은 호환되는 모양으로 데이터를 재형성하면 된다.

In [42]:
arr = np.zeros((4, 4))

In [43]:
arr_3d = arr[:, np.newaxis, :]

In [45]:
arr_3d.shape

(4, 1, 4)

In [50]:
arr_1d = np.random.normal(size=3)
arr_1d

array([ 0.73739056, -0.16250352,  1.84533983])

In [51]:
arr_1d[:, np.newaxis]

array([[ 0.73739056],
       [-0.16250352],
       [ 1.84533983]])

In [52]:
arr_1d[np.newaxis, :]

array([[ 0.73739056, -0.16250352,  1.84533983]])

In [56]:
arr = np.random.randn(3, 4, 5)
arr

array([[[ 7.90277617e-03,  1.67123033e+00, -1.61474326e+00,
         -1.45539671e+00,  1.61195860e-01],
        [-3.42229232e-01,  6.13723767e-01,  1.56027398e+00,
         -1.49288661e+00, -2.96764015e-01],
        [ 8.95630881e-01, -1.99653716e+00,  5.69729009e-01,
         -6.28722250e-01,  2.04271325e+00],
        [ 9.21900615e-01, -2.25917200e-01, -9.77826551e-02,
          5.15136479e-01, -6.88070281e-01]],

       [[-3.05026260e-01,  4.39696514e-01,  5.96519480e-01,
         -4.20821042e-01, -7.27486554e-01],
        [ 1.21065633e-02,  2.04402360e+00, -3.99862801e-01,
          1.05796922e+00, -7.81061589e-01],
        [ 1.04263776e+00, -1.98433191e+00,  5.94592885e-02,
          4.09696482e-01, -5.93715663e-01],
        [ 1.25252807e+00,  1.79014122e+00,  1.66425076e+00,
         -1.38391472e-02,  7.72670021e-02]],

       [[-1.17135220e+00, -5.16689968e-01, -6.99276412e-01,
          5.58662734e-01, -1.52129463e-01],
        [ 6.31818314e-01, -1.38250168e-01, -1.25611322e+00,


In [57]:
depth_means = arr.mean(2)
depth_means

array([[-0.2459622 ,  0.00842358,  0.17656275,  0.08505339],
       [-0.08342357,  0.386635  , -0.21325081,  0.95406958],
       [-0.39615706,  0.04020593, -0.62208703,  0.23080641]])

In [60]:
demeaned = arr - depth_means[:, :, np.newaxis]

In [62]:
demeaned.mean(2)

array([[ 4.44089210e-17, -6.66133815e-17,  0.00000000e+00,
        -2.22044605e-17],
       [ 2.22044605e-17, -1.33226763e-16,  0.00000000e+00,
         8.88178420e-17],
       [-3.88578059e-17,  4.44089210e-17,  4.44089210e-17,
         3.33066907e-17]])

- 브로드 캐스팅 이용해 배열에 값 대입하기

In [63]:
arr = np.zeros((4, 3))

In [66]:
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [69]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [71]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [72]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [30]:
arr = np.arange(16)
arr1= arr.reshape(4, 4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
arr2 = np.arange(4).reshape(2, 2)
arr2

array([[0, 1],
       [2, 3]])

In [39]:
arr2 - arr1

ValueError: operands could not be broadcast together with shapes (2,2) (4,4) 