# 1. Numpy ndarry: 다차원 배열 객체

- Numpy 핵심 기능 중 하나는 N차원 배열 객체 또는 ndarray로 파이썬에서 사용할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료 구조다.

In [1]:
import numpy as np

## 1. Basic

### 1. 리스트를 사용한 numpy 배열 생성

- np.array: 입력 데이터를 ndarray로 변환한다.
- np.asarray: 입력 데이터를 ndarray로 변환하지만 입력 데이터가 이미 ndarray일 경우 복사가 되지 않는다.

In [13]:
data1 = [5, 6, 7, 8]
arr1 = np.array(data1)
print(arr1)

arr2 = np.asarray(arr1)
print(arr2)

arr3 = np.array(arr1)
print(arr3)

print(id(arr1))
print(id(arr2))
print(id(arr3))

[5 6 7 8]
[5 6 7 8]
[5 6 7 8]
126723856
126723856
126723696


In [8]:
data1 = [5, 6, 7, 8]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([5, 6, 7, 8])

In [11]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
data3 = [[[1, 2, 6, 3, 9], [3, 1, 2, 8, 5]], 
         [[1, 2, 6, 3, 9], [3, 1, 2, 8, 5]],
         [[1, 2, 6, 3, 9], [3, 1, 2, 8, 5]]]

In [6]:
arr3 = np.array(data3)

In [9]:
arr3

array([[[1, 2, 6, 3, 9],
        [3, 1, 2, 8, 5]],

       [[1, 2, 6, 3, 9],
        [3, 1, 2, 8, 5]],

       [[1, 2, 6, 3, 9],
        [3, 1, 2, 8, 5]]])

### 2. Shape & Dimension

In [17]:
print("Shape: ", arr1.shape)
print("Dimension: ", arr1.ndim)

Shape:  (4,)
Dimension:  1


In [19]:
print("Shape: ", arr2.shape)
print("Dimension: ", arr2.ndim)

Shape:  (2, 4)
Dimension:  2


In [10]:
print("Shape: ", arr3.shape)
print("Dimension: ", arr3.ndim)

Shape:  (3, 2, 5)
Dimension:  3


### 3. 데이터 타입

- 명시적으로 지정하지 않는 한 np.array는 생성될 때 적절한 자료형을 추정한다.

In [21]:
arr1.dtype

dtype('int64')

In [22]:
arr2.dtype

dtype('int64')

### 4. Ones, Zeros, Empty, Eye

- np.array는 새로운 배열을 생성하기 위한 여러 함수를 가지고 있다.

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a = np.arange(6).reshape(2,3)
a

np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
# np.empty는 0으로 초기화된 배열을 반환하지 않는다.
np.empty((2,3,2))

array([[[-2.00000000e+000, -1.49457701e-154],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 2.12199579e-314,  3.76231868e+174]],

       [[ 6.25408382e-091,  6.40179202e+170],
        [ 9.99506565e-048,  2.00528446e-076],
        [ 3.99910963e+252,  8.34404941e-309]]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.eye(10, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
np.eye(10, 10, 1)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
arr1 = np.array([[1,2,3,4], [2,3,4,5]])

In [39]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [40]:
arr2 = np.zeros_like(arr1)

In [41]:
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
arr3 = np.ones_like(arr1)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 2. ndarray 자료형

In [65]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

- int8, uint8: 부호가 있는 8비트 정수형과 부호가 없는 8비트 정수형
- int16, uint16: 부호가 있는 16비트 정수형과 부호가 없는 16비트 정수형
- int32, uint32: 부호가 있는 32비트 정수형과 부호가 없는 32비트 정수형
- int64, uint64: 부호가 있는 64비트 정수형과 부호가 없는 64비트 정수형


- float16: 반 정밀도 부동소수점
- float32: 단 정밀도 부동소수점(C 언어의 float)
- float64: 배 정밀도 부동소수점(C 언의 double, 파이썬의 float)
- float128: 확장 정밀도 부동소수점


- complex64: 각각 2개의 32 비트 부동소수점 형을 가지는 복소수
- complex128: 각각 2개의 64 비트 부동소수점 형을 가지는 복소수
- compext256: 각각 2개의 128 비트 부동소수점 형을 가지는 복소수


- bool: True, False 값을 저장하는 불리언 형
- object: 파이썬 객체형
- string: 고정 길이 문자열형(각 글자는 1바이트)
- unicode_: 고정 길이 유니코드 형

In [57]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [58]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [59]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9])

In [61]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12], dtype=int32)

In [62]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [63]:
numeric_string

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [64]:
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

## 3. 배열과 스칼라 값의 연산

- 배열은 for 반복문을 작성하지 않고 데이터를 일괄처리할 수 있기 때문에 중요하다. 이를 벡터화라 하는데 같은 크기의 산술연산은 각 요소 단위로 적용된다.

In [66]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 브로드 캐스팅 맛보기

- 브로드 캐스팅은 다른 모양의 배열 간 산술연산을 어떻게 수행해야 하는지 설명한다. 이는 매우 강력한 기능이지만 Numpy 오랜 사용자들도 흔히 잘못 이해하고 있는 기능이다. 브로드캐스팅이 단순한 예제는 배열과 스칼라 값을 결합할 때 발생한다.

In [84]:
arr = np.arange(4)

In [85]:
arr

array([0, 1, 2, 3])

In [86]:
arr * 4

array([ 0,  4,  8, 12])

- 여기서 스칼라 값 4는 곱셈 연산 과정에 배열의 모든 원소로 전파(broadcast) 된다.

In [87]:
arr1 = np.array([[2,3,4,5],
                 [5,6,7,8]]) 

In [88]:
arr1

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [90]:
arr1 - arr

array([[2, 2, 2, 2],
       [5, 5, 5, 5]])

## 4. 색인과 슬라이싱 기초

### 1. 색인

In [91]:
arr = np.arange(10)

In [92]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr[5]

5

In [94]:
arr[5:8]

array([5, 6, 7])

In [95]:
arr[5:8] = 12

In [96]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

리스트와 중요한 차이점은 배열 조건은 원본 배열의 뷰이다. 즉, 데이터는 복사되지 않고 뷰에 대한 변경은 그대로 원본 배열에 반영된다.

In [98]:
arr_slice = arr[5:8]

In [99]:
arr_slice[1] = 12345

In [100]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [15]:
a = list(range(10))

a_slice = a[5:8]
a_slice[1] = 12345

print(a_slice)
print(a)

[5, 12345, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [101]:
arr_slice[:] = 64

In [102]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Numpy는 데이터가 복사되지 않는다. Numpy는 대용량 데이터 처리를 염두해두고 설게되었기 때문에 Numpy가 데이터 복사를 남발한다면 성능과 메모리 문제에 직면하게 될 것이다.

### 만약 View 대신 복사본을 얻고 싶다면 copy()를 사용한다.

In [105]:
arr1 = arr[5:8].copy()

In [106]:
arr1 = 100

In [107]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### 다차원 배열 다루기

In [108]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [109]:
arr2d[0][2]

3

In [110]:
arr2d[0,2]

3

In [111]:
arr3d = np.array([[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]]])

In [112]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
old_values = arr3d[0].copy()

In [116]:
arr3d[0] = 42

In [117]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [118]:
arr3d[0] = old_values

In [119]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [120]:
arr3d[1,0]

array([7, 8, 9])

### 2. 슬라이스

In [32]:
arr = np.arange(10)
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3d = np.array([[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]]])

In [23]:
arr[1:6]

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

슬라이스는 축을 따라 선택 영역 내의 요소가 선택된다.

In [124]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [125]:
arr2d[1, :2]

array([4, 5])

In [126]:
arr2d[2, :1]

array([7])

- 콜론만 쓰면 전체 축을 의미한다.

In [40]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [39]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 3. 팬시 색인

In [29]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정 순서로 로우를 선택하고 싶다면, 그냥 원하는 순서가 명시된 정수가 담긴 ndarry나 리스트를 넘기면 된다.

In [30]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

- 음수를 선택하면 끝에서부터 로우를 선택한다.

In [135]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

## 5. 배열 전치와 축 바꾸기

In [137]:
arr = np.arange(15).reshape((3,5))

In [138]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [140]:
arr = np.arange(16).reshape((2, 2, 4))

In [142]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [141]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])