In [1]:
import numpy as np

# 1. Universal 함수

ufunc라고 불리는 유니버셜 함수는 ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수이다. 유니버셜 함수는 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과 값을 반환하는 간단한 함수를 고속으로 수행할 수 있는 백터화된 래퍼 함수라고 생각하면 된다.

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### <span style="color:blue">Example 1</span>

In [0]:
# square root (sqrt)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
# Exponential


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
x = np.random.randn(8)
y = np.random.randn(8)

In [55]:
x

array([-0.21886333,  0.12502912,  0.47888623,  0.15712266,  1.16788686,
        0.07921893,  0.69323931,  0.35829684])

In [56]:
y

array([-0.69449551, -0.56268901,  1.517444  , -1.38453585, -0.1614615 ,
        0.52458238, -0.77141625,  1.64770257])

In [57]:
# x, y maximum (element wise operation)


array([-0.21886333,  0.12502912,  1.517444  ,  0.15712266,  1.16788686,
        0.52458238,  0.69323931,  1.64770257])

### 단항 유니버셜 함수

- abs: 각 원소의 절대값을 구한다.
- sqrt: 각 원소의 제곱근을 구한다.
- square: 각 원소의 제곱을 구한다.
- sign: 각 원소의 부호를 계산한다.
- ceil, floor: 각 원소의 소수자리를 올리거나 내린다.
- rint: 각 원소의 소수자리를 반올림한다.
- sin, cos, tan: 일반 삼각함수
- sinh, cosh, tanh: 쌍곡삼각 함수
- arccos, arccosh, arcsinh: 역삼각함수

### 이항 유니버셜 함수

- add, subtract, multiply: 두 배열에서 같은 위치 원소끼리 더하고, 빼고, 곱한다.
- divide: 첫 번째 배열에서 두 번째 배열의 원소를 나눈다.
- power: 첫 번째 배열의 원소에 두 번째 배열의 원소만큼 제곱한다.
- maximum, minimum: 두 원소 중 큰 값, 작은 값을 반환한다.
- mod: 첫 번째 배열의 원소에 두 번째 배열의 원소를 나눈 나머지를 구한다.
- greater, less, equal: 각각 두 원소 간의 비교 연산 결과를 불리언 배열로 반환한다.
- logical_and, logical_or, logical_xor: 각각 두 원소 간의 논리 연산을 배열로 반환한다.

# 2. 배열 연산

### 1. 조건절 표현하기

In [0]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

###### <span style="color:blue">Example 2. </span>

In [0]:
# cond가 True 이면 xarr value, False 이면 yarr value  


In [0]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [0]:
arr = np.random.randn(4, 4)
arr

array([[ 0.98806515,  0.54349433,  0.99634208, -0.78729337],
       [-0.57084269, -0.48574328,  1.64739645,  1.24734597],
       [-1.75542534, -0.11114777, -0.12206998,  1.57396286],
       [-0.06632817,  1.73308148,  0.38634245,  0.06169606]])

In [0]:
# arr가 0보다 크면 2, 작으면 -2 


array([[ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2,  2],
       [-2,  2,  2,  2]])

### 2. 수학 메서드와 통계 메서드

배열 전체 혹은 배열에서 한 축에 따르는 자료에 대한 통계를 계산하기 위한 수학 함수는 배열 메서드로 사용할 수 있다. 전체의 합이나 평균, 표준편차는 Numpy의 최상위 함수를 이용하거나, 배열의 인스턴스 메서드를 사용해서 구할 수 있다.

In [13]:
arr = np.random.rand(5, 4)
arr

array([[0.95051054, 0.39337925, 0.93902099, 0.44280456],
       [0.09654229, 0.10216378, 0.94876558, 0.80809418],
       [0.97248727, 0.28276551, 0.75766251, 0.37634574],
       [0.46131024, 0.30691609, 0.17156123, 0.78551699],
       [0.87610981, 0.19688098, 0.06236395, 0.93406581]])

In [14]:
arr.mean()

0.543263366066569

In [15]:
np.mean(arr)

0.543263366066569

- mean이나 sum 같은 함수는 선택적으로 axis 인자를 받아 해당 axis에 대한 통계를 계산하고 차수 낮은 배열을 반환한다.

###### <span style="color:blue">Example 3</span>

In [17]:
# arr 전체 합


10.86526732133138

In [16]:
# arr 전체 평균


0.543263366066569

In [31]:
arr = np.array([[0,1,2,2,2],[3,4,5,5,5],[6,7,8,8,8]])
print(arr.shape)
arr

(3, 5)


array([[0, 1, 2, 2, 2],
       [3, 4, 5, 5, 5],
       [6, 7, 8, 8, 8]])

In [29]:
# axis1 기준으로 평균


array([1.4, 4.4, 7.4])

In [32]:
# axis0 기준으로 합


array([ 9, 12, 15, 15, 15])

In [33]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# axis0 기준 누적합(cumprod)


array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [37]:
# axis1 기준 누적곱(cumprod)


array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### 3. 정렬

- np.sort 메서드는 배열을 직접 변경하지 않고 정렬된 결과를 가지고 있는 복사본을 반환한다.

In [0]:
arr = np.random.randn(8)
arr

array([-0.72457977,  0.87587823,  1.2289314 , -0.28894393,  0.15205621,
        0.39222443, -1.86491412, -0.43901666])

In [0]:
arr.sort()
arr

array([-1.86491412, -0.72457977, -0.43901666, -0.28894393,  0.15205621,
        0.39222443,  0.87587823,  1.2289314 ])

In [0]:
arr = np.random.randn(5, 3)
arr

array([[ 1.6184662 , -1.08623178, -0.94366897],
       [-0.48770058,  0.19617067, -1.26855797],
       [-0.43161619, -0.80774082,  1.70783631],
       [-1.05988322, -0.69291836, -0.12831549],
       [-0.2984775 ,  0.07530742, -1.90711257]])

In [0]:
arr.sort(1)
arr

array([[-1.08623178, -0.94366897,  1.6184662 ],
       [-1.26855797, -0.48770058,  0.19617067],
       [-0.80774082, -0.43161619,  1.70783631],
       [-1.05988322, -0.69291836, -0.12831549],
       [-1.90711257, -0.2984775 ,  0.07530742]])

## 3. 선형대수

### 내적은 중요하다.

In [40]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])
y = np.array([[6.,23.], [-1, 7], [8, 9]])

In [43]:
print(x.shape)
x

(2, 3)


array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
print(y.shape)
y

(3, 2)


array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

###### <span style="color:blue">Example 4</span>

In [0]:
# x, y dot product 


array([[ 28.,  64.],
       [ 67., 181.]])

In [51]:
from numpy.linalg import inv

In [47]:
X = np.random.randn(5, 5)
X

array([[-0.86422755,  0.61300104, -1.33128157, -0.77544552, -0.90520723],
       [ 0.30216056,  2.3591887 ,  0.74218289, -0.24390463, -0.10939491],
       [-0.02949217,  0.14939397,  0.48741788, -0.41715864,  0.56567733],
       [ 1.21631973, -0.36682   ,  0.97668664, -0.73593137,  0.5911537 ],
       [ 1.55703608,  0.58679195,  0.38057991,  1.46413045,  0.1351869 ]])

In [49]:
# mat = X.T와 X의 내적


array([[ 4.74285512,  0.64616127,  3.1409535 ,  1.99334203,  1.66208994],
       [ 0.64616127,  6.44274185,  0.87274283,  0.01600736, -0.86598784],
       [ 3.1409535 ,  0.87274283,  3.65948014,  0.48642821,  2.02843726],
       [ 1.99334203,  0.01600736,  0.48642821,  3.5200995 ,  0.25552633],
       [ 1.66208994, -0.86598784,  2.02843726,  0.25552633,  1.5190964 ]])

In [52]:
# mat의 역행렬


array([[ 0.79542438,  0.15056437, -1.03783068, -0.3556944 ,  0.66117184],
       [ 0.15056437,  0.64845324, -1.52337163, -0.04073403,  2.24592295],
       [-1.03783068, -1.52337163,  5.25256127,  0.36296676, -6.80766007],
       [-0.3556944 , -0.04073403,  0.36296676,  0.44963948, -0.19434521],
       [ 0.66117184,  2.24592295, -6.80766007, -0.19434521, 10.33811058]])