# 1. 배열 재형성하기

In [7]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

###### <span style="color:blue">Example 1. reshape</span>

In [9]:
# (8,) --> (4,2)shape으로 변경


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
# (8,) --> (4,2) --> (2,4) shape으로 변경 


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
# (15, ) --> (5, -1) shape으로 변경


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

- reshape에 넘기는 값 중 하나는 -1이 될 수도 있는데, 이 경우에는 원본 데이터를 참조해서 적절한 값을 추론하게 됩니다.

In [7]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [8]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

###### <span style="color:blue">Example 2. </span>

In [24]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
# (2,4) --> ravel


array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
# (2,4) --> flatten 


array([0, 1, 2, 3, 4, 5, 6, 7])

# 2. 배열 이어붙이고 나누기

- concatenate:  axis에 따라서 하나의 배열로 합친다.

In [28]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

In [32]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

###### <span style="color:blue">Example 3</span>

In [31]:
# axis=0 기준으로 배열 합치기


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
# axis=1 기준으로 배열 합치기


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- vstack: vertical
- hstack: horizontal

In [14]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# 3. 브로드캐스팅

- 브로드캐스팅은 다른 모양의 배열 간 산술연산을 어떻게 수행해야 하는지 설명한다. 이는 매우 강력한 기능이다. 

In [34]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [19]:
arr * 4

array([ 0,  4,  8, 12, 16])

###### <span style="color:blue">Example 4</span>

In [64]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
# axis=0 기준 평균 (arr_mean)


array([4.5, 5.5, 6.5])

In [68]:
# arr, arr_mean 차 


array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

- 브로드캐스팅 규칙을 따르기만 한다면 잠재적으로 낮은 차원의 값을 배열의 다른 차원으로 브로드캐스팅 하는 것도 가능하다.

### 브로드 캐스팅 규칙

- 만일 이어지는 각 차원(시작부터 끝까지)에 대해 축의 길이가 일치하거나 둘 중의 하나의 길이가 1이라면 두 배열은 브로드캐스팅 호환이다. 브로드캐스팅은 누락된, 혹은 길이가 1인 차원에 대해 수행된다.

In [76]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [77]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [78]:
row_means.reshape((4,1))

array([[ 1.],
       [ 4.],
       [ 7.],
       [10.]])

In [79]:
demeaned = arr - row_means.reshape((4, 1))
demeaned

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [80]:
demeaned.mean(1)

array([0., 0., 0., 0.])

###### <span style="color:blue"> Examaple 5. 브로드 캐스팅 규칙 설명</span>

- 다른 축에 대해 브로드 캐스팅하기

In [69]:
arr = np.random.randn(4, 3)
arr

array([[ 0.67137671,  0.98339825,  1.04085612],
       [ 1.71601881,  0.47155847, -1.46867186],
       [ 0.3738954 , -1.80485283,  0.14460848],
       [-2.11588053, -0.86832472,  0.71703604]])

In [83]:
# arr shape : (4,3)
# arr.mean(1) : (4,)

arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [84]:
arr.shape

(4, 3)

In [38]:
arr.mean(1).shape

(4,)

In [89]:
# arr.mean(1) 의 shape 변경 필요


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

- 브로드 캐스팅 이용해 배열에 값 대입하기

In [63]:
arr = np.zeros((4, 3))

In [66]:
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [69]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [71]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [72]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])