# 1. Numpy ndarry: 다차원 배열 객체

- Numpy 핵심 기능 중 하나는 N차원 배열 객체 또는 ndarray로 파이썬에서 사용할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료 구조다.

In [2]:
import numpy as np

## 1. Basic

### 1. 리스트를 사용한 numpy 배열 생성

- np.array: 입력 데이터를 ndarray로 변환한다.
- np.asarray: 입력 데이터를 ndarray로 변환하지만 입력 데이터가 이미 ndarray일 경우 복사가 되지 않는다.

###### <span style="color:blue">Example 1. ndarray 변환</span>

In [94]:
data1 = [5, 6, 7, 8]

In [97]:
# arr1 np.array

###### <span style="color:blue">Example 2. ndarray 변환</span>

In [4]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [34]:
# arr2 np.array

### 2. Shape & Dimension

In [27]:
print("Shape: ", arr1.shape)
print("Dimension: ", arr1.ndim)

Shape:  (4,)
Dimension:  1


###### <span style="color:blue"> Example.3 arr2의 shape 및 dim 출력 </span>

In [28]:
# shape, ndim

### 3. 데이터 타입

- 명시적으로 지정하지 않는 한 np.array는 생성될 때 적절한 자료형을 추정한다.

In [96]:
arr1.dtype

dtype('int32')

In [33]:
arr2.dtype

dtype('int32')

### 4. Ones, Zeros, Empty, Eye

- np.array는 새로운 배열을 생성하기 위한 여러 함수를 가지고 있다.

###### <span style="color:blue">Example 4. ones, zeros, empty, eye</span>

In [69]:
# (10,) 0으로 초기화된 ndarray


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
## (3, 6) 2차원 1로 초기화된 ndarray


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [75]:
# (2, 3, 2) 3차원 초기화된 되지 않은 ndarray


array([[[1.22e-321, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]]])

In [76]:
# (15, ) 시퀀스한 array 함수 - arange


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
# (10, 10) 단위 행렬 - eye, identity


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

###### <span style="color:blue">Example 5. zeros_like, ones_like</span>

In [38]:
arr1 = np.array([[1,2,3,4], [2,3,4,5]])

In [39]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [40]:
arr2 = np.zeros_like(arr1)

In [41]:
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
# arr1의 shape만큼 1 벡터를 만듬 (arr3) 


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 2. ndarray 자료형

In [83]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

- int8, uint8: 부호가 있는 8비트 정수형과 부호가 없는 8비트 정수형
- int16, uint16: 부호가 있는 16비트 정수형과 부호가 없는 16비트 정수형
- int32, uint32: 부호가 있는 32비트 정수형과 부호가 없는 32비트 정수형
- int64, uint64: 부호가 있는 64비트 정수형과 부호가 없는 64비트 정수형


- float16: 반 정밀도 부동소수점
- float32: 단 정밀도 부동소수점(C 언어의 float)
- float64: 배 정밀도 부동소수점(C 언의 double, 파이썬의 float)
- float128: 확장 정밀도 부동소수점


- complex64: 각각 2개의 32 비트 부동소수점 형을 가지는 복소수
- complex128: 각각 2개의 64 비트 부동소수점 형을 가지는 복소수
- compext256: 각각 2개의 128 비트 부동소수점 형을 가지는 복소수


- bool: True, False 값을 저장하는 불리언 형
- object: 파이썬 객체형
- string: 고정 길이 문자열형(각 글자는 1바이트)
- unicode_: 고정 길이 유니코드 형

In [98]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [99]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [100]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9])

In [101]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12])

In [108]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [109]:
numeric_string

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [110]:
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

## 3. 배열과 스칼라 값의 연산

- 배열은 for 반복문을 작성하지 않고 데이터를 일괄처리할 수 있기 때문에 중요하다. 이를 벡터화라 하는데 같은 크기의 산술연산은 각 요소 단위로 적용된다.

In [115]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [117]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 브로드 캐스팅 맛보기

- 브로드 캐스팅은 다른 모양의 배열 간 산술연산을 어떻게 수행해야 하는지 설명한다. 이는 매우 강력한 기능이지만 Numpy 오랜 사용자들도 흔히 잘못 이해하고 있는 기능이다. 브로드캐스팅이 단순한 예제는 배열과 스칼라 값을 결합할 때 발생한다.
- shape 다른 배열간 연산을 지원

###### <span style="color:blue">Example 6. broadcasting 예제</span>

In [120]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [121]:
# vector - scalar 연산


array([ 0,  4,  8, 12])

- 여기서 스칼라 값 4는 곱셈 연산 과정에 배열의 모든 원소로 전파(broadcast) 된다.

In [123]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [124]:
arr1 = np.array([[2,3,4,5],
                 [5,6,7,8]])
arr1

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [126]:
# matrix - vector 연산


## 4. 색인과 슬라이싱 기초

### 1. 색인

In [91]:
arr = np.arange(10)

In [92]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

######  <span style="color:blue">Example 7. 색인과 슬라이싱</span>

In [93]:
# 5번 index 값 구하기


5

In [94]:
# index 5 ~ index 7까지 슬라이싱 


array([5, 6, 7])

In [95]:
# index 5 ~ index 7까지 값 변경하기


In [96]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

리스트와 중요한 차이점은 배열 조건은 원본 배열의 뷰이다. 즉, 데이터는 복사되지 않고 뷰에 대한 변경은 그대로 원본 배열에 반영된다.

######   <span style="color:blue">Example 8</span>

In [98]:
# arr로 부터 일부 데이터를 arr_slice에 저장 


In [99]:
# arr_slice의 특정 index값 변경 

In [100]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [101]:
arr_slice[:] = 64

In [102]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Numpy는 데이터가 복사되지 않는다. Numpy는 대용량 데이터 처리를 염두해두고 설게되었기 때문에 Numpy가 데이터 복사를 남발한다면 성능과 메모리 문제에 직면하게 될 것이다.

### 만약 View 대신 복사본을 얻고 싶다면 copy()를 사용한다.

In [105]:
arr1 = arr[5:8].copy()

In [106]:
arr1 = 100

In [107]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### 다차원 배열 다루기

In [108]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [109]:
arr2d[0][2]

3

In [110]:
arr2d[0,2]

3

### 2. 슬라이스

In [128]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [121]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [129]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

슬라이스는 축을 따라 선택 영역 내의 요소가 선택된다.

###### <span style="color:blue">Example 9. Matrix 슬라이싱 </span>

In [127]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [125]:
# 첫번째 axis0, 0~1 axis1


array([4, 5])

In [126]:
arr2d[2, :1]

array([7])

- 콜론만 쓰면 전체 축을 의미한다.

In [127]:
# 전체 axis0, 첫번째 axis1 


array([[1],
       [4],
       [7]])

## 5. 배열 전치와 축 바꾸기

In [137]:
arr = np.arange(15).reshape((3,5))

In [138]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

###### <span style="color:blue">Example 10. 배열 전치</span>

In [141]:
# Transpose


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [151]:
arr = np.arange(24).reshape((2, 3, 4))

In [152]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [159]:
# axis1,2 바꾸기


array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])